export const FETCH_MANAGERS = "FETCH_MANAGERS";
export const FETCH_SKILLS = "FETCH_SKILLS";
export const POST_SKILLS = "POST_SKILLS";
export const POST_SKILLS_SUCCESS = "POST_SKILLS_SUCCESS";
export const REVIEW_SKILLS = "REVIEW_SKILLS";
